/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advc_2024;

public class App {
    public static void main(String[] args) {
        final long startTime = System.currentTimeMillis();

        new advc_2024.day00_template.Solution().run();
        new advc_2024.day01.Solution().run();
        new advc_2024.day02.Solution().run();
        new advc_2024.day03.Solution().run();
        new advc_2024.day04.Solution().run();
        new advc_2024.day05.Solution().run();
        new advc_2024.day06.Solution().run();
        new advc_2024.day07.Solution().run();
        new advc_2024.day08.Solution().run();
        new advc_2024.day09.Solution().run();
        new advc_2024.day10.Solution().run();
        new advc_2024.day11.Solution().run();
        new advc_2024.day12.Solution().run();
        new advc_2024.day13.Solution().run();

        System.out.println();
        System.out.println(String.format("Finished - total %dms", System.currentTimeMillis() - startTime));
    }
}
