/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advc_2018;

public class App {
    public static void main(String[] args) {
        final long startTime = System.currentTimeMillis();

        new advc_2018.day01.Solution().run();
        new advc_2018.day02.Solution().run();
        new advc_2018.day03.Solution().run();
        new advc_2018.day04.Solution().run();
        new advc_2018.day05.Solution().run();
        new advc_2018.day06.Solution().run();
        new advc_2018.day07.Solution().run();
        new advc_2018.day08.Solution().run();
        new advc_2018.day09.Solution().run();
        new advc_2018.day10.Solution().run();

        System.out.println();
        System.out.println(String.format("Finished - total %dms", System.currentTimeMillis() - startTime));
    }
}
